### ISSUE TITLE
'Attempted to load class' error

### ISSUE THREAD

**Issue by sietsevandreven** [respinar/contao-products#11]
Contao 5.2.7
PHP 8.1

I get the following error when clicking on the products item in the menu:

Attempted to load class "Table" from the global namespace.
Did you forget a "use" statement for e.g. "Symfony\Component\Console\Helper\Table", "Spatie\SchemaOrg\Table", "League\CommonMark\Extension\Table\Table", "Doctrine\ORM\Mapping\Table" or "Doctrine\DBAL\Schema\Table"?

**Comment by hamidpeywasti** [comment]
Hi,
I just fixed this error in version 0.26.0
Please update to this new version and check it.
Thanks

**Comment by sietsevandreven** [comment]
I have installed the latest version. The error I got is gone :)

But when I click on the products menu with debug mode enabled, I get the following error:
Warning: Undefined array key "validImageTypes"

Whit debug mode disabled I am able to go into the products screen, and when adding a new catalog I get the following error:
An exception has been thrown during the rendering of a template ("call_user_func_array(): Argument #1 ($callback) must be a valid callback, class "Respinar\ProductsBundle\Model\ProductModel" not found").

**Comment by hamidpeywasti** [comment]
I'll fix it.

**Comment by sietsevandreven** [comment]
Hi, product creating works like a charm now :) Thank you very much.

However, creating a product list content element gives the following error:
_Tried to list template options for the modern fragment type "content_element/product_list" but could not find any template. In case you wanted to use the legacy type "ce_product_list", define it explicitly in the "template" property of your controller's service tag/attribute._

Is this someting I can fix myself?

**Comment by hamidpeywasti** [comment]
I'll fix it.

**Comment by hamidpeywasti** [comment]
I fixed it. Please update it.
